name: t3r_c0d3
description: "Una app de herramientas automatizadas para usuarios de Termux"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  android_intent_plus: ^5.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  http: ^1.1.0
  dio: ^5.3.3
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Solo assets que existen
  assets:
    - assets/images/
    - assets/icons/
    - assets/readmes/
    - assets/scripts/